services:

  # MySQL Service Configuration
  db:
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: ev_charg_now 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  # PhpMyAdmin Service Configuration
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306 
      PMA_ARBITRARY: 1 
    ports:
      - "8080:80"
    depends_on:
      - db